networks:
  demo:


volumes:
  n8n_storage:
  postgres_storage:
  ollama_storage:
  caddy_data:
  caddy_config:


x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: [ 'demo' ]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
    - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
    - OLLAMA_HOST=ollama:11434
    - WEBHOOK_URL=http://localhost:5678/
  env_file:
    - path: .env
      required: true

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: [ 'demo' ]
  restart: unless-stopped
  ports:
    - "11434:11434"
  volumes:
    - ollama_storage:/root/.ollama
  environment:
    - OLLAMA_HOST=0.0.0.0
    - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-4}

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: [ 'demo' ]
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n-import:
    <<: *service-n8n
    hostname: n8n-import
    container_name: n8n-import
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        echo "Starting credentials import..."
        n8n import:credentials --input=/demo-data/credentials/ollama_credential.json || true
        n8n import:credentials --input=/demo-data/credentials/qdrant_credential.json || true
        echo "Starting workflows import..."
        n8n import:workflow --separate --input=/demo-data/workflows || true
        echo "Import successfully completed."
    volumes:
      - ./n8n/demo-data:/demo-data
    depends_on:
      postgres:
        condition: service_healthy

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/demo-data:/demo-data
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy
      n8n-import:
        condition: service_completed_successfully

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: [ 'demo' ]
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant/storage:/qdrant/storage

  ollama-cpu:
    <<: *service-ollama

  ollama-pull-llama:
    image: ollama/ollama:latest
    networks: [ 'demo' ]
    container_name: ollama-pull-llama
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: /bin/sh
    environment:
      # Point exactly to the main service name
      - OLLAMA_HOST=ollama-cpu:11434
    command:
      - "-c"
      # Add a very lightweight and excellent embedding model for RAG
      - "sleep 5; ollama pull llama3.2:latest && ollama pull nomic-embed-text-v2-moe"
    depends_on:
      - ollama-cpu

  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    networks: [ 'demo' ]
    ports:
      - "80:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - n8n
